# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Aruz Parajuli
#url:              http://lanyon.getpoole.com
baseurl:          '/'
paginate:         5

author:
  name:           'Aruz Parajuli'
  url:            https://twitter.com/aruzmeister

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/aruzmeister
